
#https://github.com/hn/jura-coffee-machine
esphome:
  name: coffee_jura_j6
  platform: ESP32
  board: esp32cam

wifi:
  ssid: "bwlan-q"
  password: "lianabirkler"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Coffee Jura J6 Fallback Hotspot"
    password: "R4FTYe2bg5aB"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


# ESP32-CAM
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32

  name: Kitchen
  resolution: 640x480
  jpeg_quality: 25

  # ... Frame Settings

# Flashlight
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4
light:
  - platform: binary
    output: gpio_4
    name: $hostname light


sensor:
  - platform: ultrasonic
    timeout: 3m
    trigger_pin: 15
    echo_pin: 14
    name: "Distance 1"
    update_interval: 2s
  - platform: ultrasonic
    timeout: 3m
    trigger_pin: 12
    echo_pin: 13
    name: "Distance 2"
    update_interval: 2s




