#
#
# INPUT: Temperate Exterior
# INPUT: Temperature Interiorr
# INPUT: Temperature HVAC out
# INPUT: Temperature Floor
# INPUT: Cooling Requested
# INPUT: Heat Requested
# INPUT: Cooling Requested Stage 2
# INPUT: Heat Requested  Stage 2
# INPUT: Damper Closed
# INPUT: Damper Opened
# OUTPUT: Cooling Inhibit
# OUTPUT: Heating Inhibit
# OUTPUT: Damper Motor On
# OUTPUT: Damper Motor Direction
# 
# 
# 
#
#                        fresh_air
#                       | 
# [fresh_air_intake] ===o=====   - fully_opened_switch
#                            |                                               conditioned_air
#                           \ /                                              |
#        damper_motor -      o>====[Filter]====[FAN}====[Furnace+]====[AC-]==o==[House]
#                           / \
#                            |
# [inside_intake] ======o====+   - fully_closed_switch
#                       |
#                        inside_air
#

esphome:
  name: hvac-fresh-air-controller
  platform: ESP32
  board: esp32-gateway

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:


#wifi:
#  ssid: "bwlan-q"
#  password: "lianabirkler"

#  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Freshaircontroller"
#    password: "l7sRgxEASkWi"


i2c:
  sda: 14
  scl: 13
  scan: True
  frequency: 100kHz
  id: bus_a

pcf8574:
  - id: 'pcf8574_hub'
    address: 0x20
    pcf8575: False


globals:
   - id: global_fresh_air_damper_position
     type: int
     restore_value: no
     initial_value: '-1'

binary_sensor:
  - platform: status
    name: "Fresh Air Controller"
  

  - platform: gpio
    id: call_cool_stage1
    pin:
      number: GPIO16
      inverted: true
      mode: INPUT_PULLUP

  - platform: gpio
    id: call_cool_stage2
    pin:
      number: GPIO32
      inverted: true
      mode: INPUT_PULLUP

  - platform: gpio
    id: call_heat_stage1
    pin:
      number: GPIO36
      inverted: true
      mode: INPUT_PULLUP

  - platform: gpio
    id: call_heat_stage2
    pin:
      number: GPIO16
      inverted: true
      mode: INPUT_PULLUP

  - platform: gpio
    id: call_fan_on
    pin:
      number: GPIO35
      inverted: true
      mode: INPUT_PULLUP

  - platform: gpio
    id: damper_fully_opened_switch
    pin: 
      pcf8574: pcf8574_hub
      number: 7
      mode: INPUT

    on_press:
      then:
        - switch.turn_off: damper_motor_open_switch

  - platform: gpio
    id: damper_fully_closed_switch
    pin: 
      pcf8574: pcf8574_hub
      number: 6
      mode: INPUT
    on_press:
      then:
        - switch.turn_off: damper_motor_close_switch


sensor:
  # Example source sensor
  - platform: adc
    pin: GPIO39
    id: adc_sensor_raw_ct1
    attenuation: 6dB
    internal: True

  - platform: ct_clamp
    id: adc_sensor_current_transformer
    sensor: adc_sensor_raw_ct1
    name: "Current HVAC"
    unit_of_measurement: "A"
    accuracy_decimals: 2
    update_interval: 15s
    filters:
      - calibrate_linear:
          # Measured value of 0 maps to 0A
          - 0 -> 0
          - 0.78 -> 9.6




switch:
  - platform: gpio
    pin: 
      pcf8574: pcf8574_hub
      number: 7
      inverted: true
      mode: OUTPUT
    name: "Damper Open"
    id: damper_motor_open_switch
    icon: mdi:valve
    restore_mode: ALWAYS_OFF
    interlock: &damper_motor_interlock_group [damper_motor_open_switch, damper_motor_close_switch]
    interlock_wait_time: 2s
    on_turn_on:
      then:
        - delay: 60s
        - switch.turn_off: damper_motor_open_switch

  - platform: gpio
    pin: 
      pcf8574: pcf8574_hub
      number: 6
      inverted: true
      mode: OUTPUT
    name: "Damper Close"
    id: damper_motor_close_switch
    icon: mdi:valve
    restore_mode: ALWAYS_OFF
    interlock: *damper_motor_interlock_group
    interlock_wait_time: 2s
    on_turn_on:
      then:
        - delay: 60s
        - switch.turn_off: damper_motor_close_switch

  - platform: gpio
    pin: 
      pcf8574: pcf8574_hub
      number: 5
      inverted: true
      mode: OUTPUT
    name: "Cooling Inhibit"
    id: cooling_compressor_inhibit
    icon: mdi:valve
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 
      pcf8574: pcf8574_hub
      number: 4
      inverted: true
      mode: OUTPUT
    name: "Heating Inhibit"
    id: heating_inhibit
    icon: mdi:valve
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 
      pcf8574: pcf8574_hub
      number: 3
      inverted: true
      mode: OUTPUT
    name: "Fan Force On"
    id: fan_force_on
    icon: mdi:valve
    restore_mode: ALWAYS_OFF

cover:
  - platform: template
    id: fresh_air_damper
    name: Fresh Air Damper
    device_class: damper
    lambda: |-
      if (id(damper_fully_opened_switch).state) {
        return COVER_OPEN;
      } else if (id(damper_fully_closed_switch).state) {
        return COVER_CLOSED;
      } else {
        return 0.5;
      }
    open_action:
      - switch.turn_on: damper_motor_open_switch
    close_action:
      - switch.turn_on: damper_motor_close_switch
    stop_action:
      - switch.turn_off: damper_motor_close_switch
      - switch.turn_off: damper_motor_close_switch
    optimistic: true
    has_position: true





